import Head from "next/head";
import styles from "../styles/Home.module.scss";
import { useEffect } from "react";
import Hero from "../components/Hero/Hero";
import MainSection from "../components/MainSection";
import MainModal from "../components/MainModal/MainModal";

export default function Home({
  isModalVisibile,
  movieID,
  setMovieID,
  setModalVisibility,
  navBarPage,
}) {
  useEffect(() => {
    navBarPage.current.childNodes.forEach(
      (node) => (node.style = "border: none")
    );

    navBarPage.current.firstChild.style =
      "@media only screen and (min-width: 769px) {border-bottom: 4px solid #fffffff5; border-top: 4px solid #ffffff00}";
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Movie Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero setMovieID={setMovieID} setModalVisibility={setModalVisibility} />
      <MainSection
        setModalVisibility={setModalVisibility}
        setMovieID={setMovieID}
      />
    </div>
  );
}
