import Head from "next/head";
import styles from "../styles/Home.module.scss";
import { useState } from "react";
import Hero from "../components/Hero/Hero";
import MainSection from "../components/MainSection";
import NavBar from "../components/NavBar/NavBar";
import MainModal from "../components/MainModal/MainModal";

export default function Home() {
  const [isModalVisibile, setModalVisibility] = useState(false);
  const [movieID, setMovieID] = useState("");

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar setMovieID={setMovieID} setModalVisibility={setModalVisibility} />
      <Hero setMovieID={setMovieID} setModalVisibility={setModalVisibility} />
      <MainSection
        setModalVisibility={setModalVisibility}
        setMovieID={setMovieID}
      />
      {isModalVisibile && (
        <MainModal movieID={movieID} setModalVisibility={setModalVisibility} />
      )}
    </div>
  );
}
