import styles from "./index.module.scss";
import { useEffect } from "react";
import Footer from "../../components/Footer/Footer";
import Link from "next/link";
import Head from "next/head";

export default function Aboutus(props) {
  const { setLinkActive } = props;

  useEffect(() => {
    setLinkActive("Aboutus");
  }, []);

  return (
    <>
      <Head>
        <title>Movie Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.aboutus}>
        <div className={styles.maincontent}>
          <div className={styles.text_container}>
            <h2>HELLO THERE!</h2>
            <h3>It&apos;s just an excercise</h3>
            <p>
              if you are curious,{" "}
              <a
                href="https://github.com/marco94gug/EDGEMONY/tree/main/movienewnextapp"
                target="_blank"
                rel="noopener noreferrer"
              >
                HERE
              </a>{" "}
              you can find the complete code of this App.
            </p>
            <a
              href="https://marcoguglielmino.com/"
              target="_blank"
              rel="noopener noreferrer"
              style={{ textAlign: "right" }}
            >
              ...About me
            </a>
            <div className={styles.vercel}>
              <p>
                build with{" "}
                <a
                  href="https://nextjs.org/"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Next.js
                </a>
              </p>
              <p>
                deployed with{" "}
                <a
                  href="https://vercel.com/"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Vercel.app
                </a>
              </p>
            </div>
          </div>
        </div>
        <Footer />
      </div>
    </>
  );
}
