import Head from "next/head";
import styles from "../styles/Home.module.scss";
import { useEffect } from "react";
import Hero from "../components/Hero/Hero";
import MainSection from "../components/MainSection";

import Footer from "../components/Footer/Footer";

export default function Home({
  setMovieID,
  setModalVisibility,
  setLinkActive,
}) {
  useEffect(() => {
    setLinkActive("Home");
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Movie Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero setMovieID={setMovieID} setModalVisibility={setModalVisibility} />
      <MainSection
        setModalVisibility={setModalVisibility}
        setMovieID={setMovieID}
      />
    </div>
  );
}
